sudo: true

services:
  - docker

branches:
  only:
    - master

before_install:
#  - openssl aes-256-cbc -K $encrypted_62b461b4c6ca_key -iv $encrypted_62b461b4c6ca_iv -in configs.tar.enc -out ./configs.tar -d
#  - tar -xvf configs.tar
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce=17.09.0~ce-0~ubuntu
  - sudo docker --version
  - sudo pip install awscli

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build --build-arg version=$TRAVIS_BUILD_NUMBER -f ./HomepageCore.UI/Dockerfile -t $CONTAINER_REGISTRY/homepagecore:latest .
  - docker push $CONTAINER_REGISTRY/homepagecore:latest
  - docker build -f ./HomepageCore.Identity/Dockerfile -t $CONTAINER_REGISTRY/homepagecore.identity:latest .
  - docker push $CONTAINER_REGISTRY/homepagecore.identity:latest

deploy:
  provider: script
  script: ./go.sh deploy
  skip_cleanup: true
  on:
    branch: master