version: "3"
services:
  web:
    build: 
      args:
        configuration: Release
    image: hailedev/homepagecore:latest
    ports:
      - "80:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production 