version: "3"
services:
  nginx:
    build: 
      context: .
      dockerfile: ./deploy/nginx
    image: hailedev/nginx:latest
    volumes:
      - "/var/homepagecore/certs:/root/certs/haile.info"
    ports:
     - "80:80"
  identity:
    build: 
      args:
        configuration: Release
    image: hailedev/homepagecore.identity:latest
    volumes:
      - "/var/homepagecore/data:/data/db"
      - "/var/homepagecore/images:/var/www/wwwroot/images/blog"
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
  web:
    build: 
      args:
        configuration: Release
    image: hailedev/homepagecore:latest
    volumes:
      - "/var/homepagecore/data:/data/db"
      - "/var/homepagecore/images:/var/www/wwwroot/images/blog"
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 