version: "3"
services:
  web:
    build: 
      args:
        configuration: Debug
    image: hailedev/homepagecore:dev
    ports:
      - "8080:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 