version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
      - "certs:/root/certs/hai.codes"
    deploy:
      replicas: 1
    ports: 
      - "443:443"
      - "80:80"
    configs:
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "web"
      - "identity"
      - "viz"

  identity:
    image: hailedev/homepagecore.identity:latest
    volumes:
      - "db-data:/data/db"
      - "images:/var/www/wwwroot/images/blog"
      - "certs:/certificates"
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - CONNECTIONSTRINGS__DEFAULTCONNECTION_FILE=/run/secrets/id_connectionstrings_defaultconnection
      - CONNECTIONSTRINGS__IDSERVERDBCONNECTION_FILE=/run/secrets/id_connectionstrings_idserverdbconnection
      - AUTHENTICATION__GOOGLE__CLIENTSECRET_FILE=/run/secrets/id_google_clientsecret
      - AUTHENTICATION__GOOGLE__CLIENTID_FILE=/run/secrets/id_google_clientid
      - AUTHENTICATION__FACEBOOK__CLIENTSECRET_FILE=/run/secrets/id_facebook_clientsecret
      - AUTHENTICATION__FACEBOOK__CLIENTID_FILE=/run/secrets/id_facebook_clientid
      - ASPNETCORE_URLS=http://*:8080
    secrets:
      - id_connectionstrings_defaultconnection
      - id_connectionstrings_idserverdbconnection
      - id_google_clientsecret
      - id_google_clientid
      - id_facebook_clientsecret
      - id_facebook_clientid

  web:
    image: hailedev/homepagecore:latest
    volumes:
      - "db-data:/data/db"
      - "images:/var/www/wwwroot/images/blog"
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTIONSTRINGS__DEFAULTCONNECTION_FILE=/run/secrets/web_connectionstrings_defaultconnection
      - OPENIDCONNECT__CLIENTID_FILE=/run/secrets/web_openidconnect_clientid
      - OPENIDCONNECT__CLIENTSECRET_FILE=/run/secrets/web_openidconnect_clientsecret
      - OPENIDCONNECT__AUTHORITY_FILE=/run/secrets/web_openidconnect_authority
      - OPENIDCONNECT__REDIRECTURI_FILE=/run/secrets/web_openidconnect_redirecturi
      - EMAIL__SERVER_FILE=/run/secrets/web_email_server
      - EMAIL__ACCOUNT_FILE=/run/secrets/web_email_account
      - EMAIL__PASSWORD_FILE=/run/secrets/web_email_password
      - EMAIL__ADMIN_FILE=/run/secrets/web_email_admin
      - EMAIL__RETURNADDRESS_FILE=/run/secrets/web_email_returnaddress
      - ASPNETCORE_URLS=http://*:8080
    secrets:
      - web_connectionstrings_defaultconnection
      - web_openidconnect_clientid
      - web_openidconnect_clientsecret
      - web_openidconnect_authority
      - web_openidconnect_redirecturi
      - web_email_server
      - web_email_account
      - web_email_password
      - web_email_admin
      - web_email_returnaddress
  viz:
    image: dockersamples/visualizer:latest
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role==manager
      replicas: 1

volumes:
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/homepagecore/certs"
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/homepagecore/data"
  images:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/homepagecore/images"

configs:
  default.conf:
    file: ./default.stack.conf
  nginx.conf:
    file: ./nginx.conf

secrets:
  web_connectionstrings_defaultconnection:
    external: true
  web_openidconnect_clientid:
    external: true
  web_openidconnect_clientsecret:
    external: true
  web_openidconnect_authority:
    external: true
  web_openidconnect_redirecturi:
    external: true
  web_email_server:
    external: true
  web_email_account:
    external: true
  web_email_password:
    external: true
  web_email_admin:
    external: true
  web_email_returnaddress:
    external: true
  id_connectionstrings_defaultconnection:
    external: true
  id_connectionstrings_idserverdbconnection:
    external: true
  id_google_clientsecret:
    external: true
  id_google_clientid:
    external: true
  id_facebook_clientsecret:
    external: true
  id_facebook_clientid:
    external: true