version: "3"
services:
  web:
    image: hailedev/homepagecore:latest
    volumes:
      - "db-data:/data/db"
      - "images:/var/www/wwwroot/images/blog"
    deploy:
      replicas: 1
    ports: 
      - "80:80"
  identity:
    image: hailedev/homepagecore.identity:latest
    volumes:
      - "db-data-id:/data/db"
    deploy:
      replicas: 1
    ports: 
      - "8080:80"
  viz:
    image: dockersamples/visualizer:latest
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role==manager
    ports:
      - "8090:8080"

volumes:
  db-data:
    driver: "cloudstor:aws"
  images:
    driver: "cloudstor:aws"
  db-data-id:
    driver: "cloudstor:aws"