version: "3"
services:
  web:
    image: hailedev/homepagecore:latest
    volumes:
      - "db-data:/data/db"
    deploy:
      replicas: 1
    ports: 
      - "80:80"

  viz:
    image: dockersamples/visualizer:latest
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role==manager
    ports:
      - "8090:8080"

volumes:
  db-data:
    driver: "cloudstor:aws"