version: "3"
services:
  nginx:
    image: hailedev/nginx
    volumes:
      - "certs:/root/certs/haile.info"
    deploy:
      replicas: 1
    ports: 
      - "443:443"
      - "80:80"
  web:
    image: hailedev/homepagecore:latest
    volumes:
      - "db-data:/data/db"
      - "images:/var/www/wwwroot/images/blog"
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_URLS=http://*:8080
  identity:
    image: hailedev/homepagecore.identity:latest
    volumes:
      - "db-data:/data/db"
      - "images:/var/www/wwwroot/images/blog"
      - "certs:/certificates"
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_URLS=http://*:8080
  viz:
    image: dockersamples/visualizer:latest
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role==manager
      replicas: 1

volumes:
  certs:
    driver: "cloudstor:aws"
  db-data:
    driver: "cloudstor:aws"
  images:
    driver: "cloudstor:aws"