version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - "config:/etc/nginx/conf.d"
    deploy:
      replicas: 1
    ports: 
      - "80:80"
  web:
    image: hailedev/homepagecore:latest
    volumes:
      - "db-data:/data/db"
      - "images:/var/www/wwwroot/images/blog"
    deploy:
      replicas: 1
    ports: 
      - "8060:8060"
    environment:
      - ASPNETCORE_URLS=http://*:8060
  identity:
    image: hailedev/homepagecore.identity:latest
    volumes:
      - "db-data:/data/db"
      - "images:/var/www/wwwroot/images/blog"
    deploy:
      replicas: 1
    ports: 
      - "8080:80"
  viz:
    image: dockersamples/visualizer:latest
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role==manager
      replicas: 1
    ports:
      - "8090:8080"

volumes:
  config:
    driver: "cloudstor:aws"
  db-data:
    driver: "cloudstor:aws"
  images:
    driver: "cloudstor:aws"